game:
  shared: # Shared with players
    num_players: 2
    num_games: 10000
  private: # Hidden from players
    with_replacement: True
    num_cards: 7
    alternate: True
    draw_skip: True
    

players:
  - player: onestepacsoft
  # - player: onestepac
    sampler: esnd
    epsilon: .7
  - player: random

