game:
  shared: # Shared with players
    num_players: 2
    num_games: 10000
  private: # Hidden from players
    with_replacement: True
    num_cards: 7
    alternate: True
    draw_skip: True
    

players:
  - player: qlearn
    epsilon: .3
    sampler: egnd
    hyper:
      er_size: 4
      minibatch_size: 4
      num_iters_p2t: 32
  - player: decent4

