game:
  shared: # Shared with players
    num_players: 2
    num_games: 10000
  private: # Hidden from players
    with_replacement: True
    num_cards: 7
    alternate: True
    draw_skip: True
    

players:
  # - player: reinvalactsoft
  # - player: reinvalactsoft2
  - player: reinvalactsoft2
    epsilon: .7
    sampler: esnd
  - player: random

