game:
  shared: # Shared with players
    num_players: 2
    num_games: 50
  private: # Hidden from players
    with_replacement: True
    num_cards: 4
    alternate: True
    draw_skip: True
    

players:
  # - player: reinvalactsoft
  # - player: reinvalactsoft2
  - player: reinvalact
    epsilon: .3
  - player: decent4

