game:
  shared: # Shared with players
    num_players: 2
    num_games: 100
  private: # Hidden from players
    with_replacement: True
    num_cards: 4
    alternate: True
    draw_skip: True
    

players:
  - player: sarsa
    epsilon: .1
    hyper:
      er_size: 1024
      minibatch_size: 32
      num_iters_p2t: 32
  - player: noob

